### ISSUE TITLE
[SSOC'23] Find minimum in rotated sorted array 

### ISSUE THREAD

**Issue by Nikita06211** [Kumar-laxmi/Algorithms#1243]
**Describe the solution you'd like**
Suppose an array of length n sorted in ascending order is rotated between 1 and n times. the algorithm will return the minimum element of this sorted rotated array of unique elements. The solution will be in c++.

**Additional context**
Example:
Input: nums = [3,4,5,1,2]
Output: 1
Explanation: The original array was [1,2,3,4,5] rotated 3 times

kindly assign me this issue under SSOC'23.

**Comment by TusharGagal** [comment]
@Kumar-laxmi please assign me this task under ssoc'23

**Comment by himughanakash** [comment]
@Kumar-laxmi please this issue to me so that i start working on this under ssoc'23 program.

**Comment by chhavisharma30** [comment]
I can solve this issue.
It can be solved by two approaches.
We can either sort the array so that the first element will be minimum.
Or we can linearly travel in the array and when we find an element which is smaller than its previous element, then that is the minimum element in the rotated sorted array.
Kindly assign me this issue so that I can work on this.

**Comment by shivangi2002** [comment]
@kum

> **Describe the solution you'd like** Suppose an array of length n sorted in ascending order is rotated between 1 and n times. the algorithm will return the minimum element of this sorted rotated array of unique elements. The solution will be in c++.
> 
> **Additional context** Example: Input: nums = [3,4,5,1,2] Output: 1 Explanation: The original array was [1,2,3,4,5] rotated 3 times
> 
> kindly assign me this issue under SSOC'23.

@Kumar-laxmi  kindly assign me this issue.
