### ISSUE TITLE
Binary Search on a 2D matrix

### ISSUE THREAD

**Issue by Arbtrage** [Kumar-laxmi/Algorithms#135]
**Is your feature request related to a problem? Please describe.**
Searching an element in a 2d matrix in logarithmic time.

**Describe the solution you'd like**
Apply binary search for 2d matrix

**Additional context**
@Kumar-laxmi Please assign me this issue in C++.

**Comment by Gaurav-8604** [comment]
I can provide detailed solution with images and language in c++ with standard template library

**Comment by Sachittarway** [comment]
Please assign me the task I can provide detailed solution in c++ with proper use of dynamic memory and reference variables which will be  compatible for all systems.

**Comment by MaYaNkKashyap681** [comment]
Assign this to me in C.

**Comment by VishalS-HK** [comment]
Can I be assigned this in Java?

**Comment by Gaurav-8604** [comment]
**Is your feature request related to a problem? Please describe.**
Normally, many of the people apply linear search on a 2D matrix or an array which increases the time complexity of that code. 
O(N*M) is the time complexity of linear search.
But in binary search, each search is divide into half which saves a lot of time with large amount of data.
O(N+M) is the time complexity of binary search.
Point to be noted that binary search only works when the matrix is row wise or column wise sorted. Otherwise it will have time complexity of O((M * N) log(M * N)) + O(N + M) which is far worse than linear search.

**Describe the solution you'd like**
Here we apply binary search on a 2D array in which every row is increasingly sorted from left to right, and the last number in each row is not greater than the first number of the next row.
But, as we can see each row in the matrix is sorted and the first element of a row is greater than or equal to the last number of the preceding row; therefore, the matrix can be viewed as a sorted one dimensional array. If all rows in the input matrix are concatenated in top down order, it forms a sorted one dimensional array. And, in that case binary search algorithm is suitable for this 2D array.

**Additional context**
@Kumar-laxmi Please assign me this issue in C++. and under SWOC S3

**Comment by Kumar-laxmi** [comment]
Assigned!
@Arbtrage : C++
@MaYaNkKashyap681 : C
@VishalS-HK : Java
@Gaurav-8604 : Python

**Comment by RitikaRathore05** [comment]
I want  to work on this issue under SWOC S3. please assign it to  me.
