### ISSUE TITLE
Detection of cycle in linked list in C, Java & Python

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#1403]
**Is your feature request related to a problem? Please describe.**
Given a linked list, check if the linked list has a loop (cycle) or not. The below diagram shows a linked list with a loop. 
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/97d0bb5a-f78f-4bba-b2e6-d339241eba07)

**Describe the solution you'd like**
Follow the steps below to solve the problem:
- Traverse the list individually and keep putting the node addresses in a Hash Table. 
- At any point, if NULL is reached then return false 
- If the next of the current nodes points to any of the previously stored nodes in  Hash then return true.

**Additional context**
![image](https://github.com/Kumar-laxmi/Algorithms/assets/76027425/d0ea27df-739a-4c86-95a0-fab92e51df65)

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi I can do this

**Comment by vedang2003** [comment]
@Kumar-laxmi Please assign me this issue for SSOC'23.
This shall be my first PR for SSOC

**Comment by Kumar-laxmi** [comment]
Assigned!
@vedang2003 : C, Java & Python

**Comment by Kumar-laxmi** [comment]
@vedang2003 What is your status on this issue?

**Comment by vedang2003** [comment]
Sorry for the delay I'll push the code today itself.

**Comment by vedang2003** [comment]
Please check the PR.

**Comment by NupurHardiya** [comment]
Hello @Kumar-laxmi 
Please assign me this issue for SSOC'23.
my approach will be :-

1. Create a hash table to store the addresses of all the nodes in the linked list.
2. Start traversing the linked list, and for each node, check if the node's address is already in the hash table.
3. If the node's address is already in the hash table, then the linked list contains a loop.
4. Otherwise, the node's address is added to the hash table, and the traversal continues.
5. The code returns True if the linked list contains a loop, and False otherwise.

Here is an example of how the approach works:

Let's say we have the following linked list:

1 -> 2 -> 3 -> 4 -> 5 -> 1

The hash table will start out empty.

When we traverse the linked list, we will first add the node with the address 1 to the hash table.

Then, we will add the node with the address 2 to the hash table.

Then, we will add the node with the address 3 to the hash table.

Then, we will add the node with the address 4 to the hash table.

Finally, we will add the node with the address 5 to the hash table.

At this point, the hash table will contain all the nodes in the linked list.

When we try to add the node with the address 1 to the hash table again, we will find that the address is already in the hash table.

This means that the linked list contains a loop.

The code will return True to indicate that the linked list contains a loop.

**Comment by Kumar-laxmi** [comment]
Assigned!
@NupurHardiya : C, Java & Python
