### ISSUE TITLE
Middle of a LinkedList in java

### ISSUE THREAD

**Issue by linga66** [Kumar-laxmi/Algorithms#1572]
**Is your feature request related to a problem? Please describe.**
The middle of the linkedlist code is not mentioned, but it is very important

**Describe the solution you'd like**
to add the algorithm which gives middle node of the linked list 

**Additional context**
Assign me this @Kumar-laxmi

**Comment by Shanukumar2929** [comment]
Since I have a good understanding of linked list ,I can solve this problem.
Approach1:
 Traverse the whole linked list and count the no. of nodes. Now traverse the list again till count/2 and return the node at count/2.
Approach2:Using two pointers.
Move one pointer by 1 and other pointer by 2.So, when the second one reaches the end ,the first pointer will be at the middle node.

So,can you please this issue to me under ssoc'23

**Comment by jinx-vi-0** [comment]
@Kumar-laxmi  please assign this to me under SSOC'23. I'm ready to contribute in Java

Is your feature request related to a problem?
-- Middle of a LinkedList in java

Describe the solution you'd like

Method 1: Easy And Brute Force Way:
The Approach: Traverse the whole linked list and count the no. of nodes. Now traverse the list again till count/2 and return 
the node at count/2. 

Time Complexity: O(n) where n is no of nodes in linked list
Auxiliary Space: O(1)

Method 2: Traverse linked list using two-pointers. Move one pointer by one and the other pointers by two. When the fast pointer reaches the end, the slow pointer will reach the middle of the linked list.

Time Complexity: O(n)
Auxiliary Space: O(1)

**Comment by dhruvdd8888** [comment]
I can help, I suggest you to use fast, slow pointer.
