### ISSUE TITLE
GCD and LCM 

### ISSUE THREAD

**Issue by Shubh08am** [Kumar-laxmi/Algorithms#174]
**Is your feature request related to a problem? Please describe.**
 We are given two numbers. We need to find there greatest common divisor (GCD) and least common divisor (LCM).

**Describe the solution you'd like**
Using Recursion to find greatest common divisor (GCD) and least common divisor (LCM) of given numbers.

**Describe alternatives you've considered**
Using Recursion in place of iterative process.

Please Assign this task to me Using C++

**Comment by Gaurav-8604** [comment]
**Is your feature request related to a problem? Please describe.**
We know the concepts of Greatest Common Divisor and Least Common Multiplier. We also require them in various competitive coding questions as well as real life examples as well as an approach to simple mathematical calculation. 

Example like: 
Five bright coloured lights flash once in 2,4,6,8 and 10 seconds respectively. After how much time will they all flash together ??

Answer LCM(2,4,6,8,10) = 120 seconds. The disco will be brilliantly lit with multi color bulbs every 120 seconds. Fact can be used to make Disco more attractive by tweaking the flash interval of individual flash lights.

**Describe the solution you'd like**
I will be providing solutions based on recursion,loops as well as inbuilt standard template library functions provided in c++.


**Describe alternatives you've considered**
We can use recursion instead of iterations.
We can also use given __gcd() and lcm() instead of recursion to simplify the process.

Please Assign this task to me Using C++ and SWOC S3

**Comment by Kumar-laxmi** [comment]
Since this is an easy task, @Shubh08am you have to code GCD and LCM in all four languages

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented in all four languages
