### ISSUE TITLE
Order Agnostic Binary Search

### ISSUE THREAD

**Issue by VishalS-HK** [Kumar-laxmi/Algorithms#348]
**Is your feature request related to a problem? Please describe.**

Order-Agnostic Binary Search is a modified version of Binary Search Algorithm. Here in this modified binary search comes with one more condition checking. 

The intuition behind this algorithm is what if the order of the sorted array is not given. So here check that the value of the first element is greater or smaller than the last element.

**Comment by VishalS-HK** [comment]
This can be done in C, C++, Java, JS and Python.

Can I be assigned this in Java and C?

**Comment by VaibhavArora314** [comment]
Please assign me this issue in C++.

**Comment by Kumar-laxmi** [comment]
> This can be done in C, C++, Java, JS and Python.
> 
> Can I be assigned this in Java and C?

Please implement in all four languages

**Comment by Kumar-laxmi** [comment]
Assigned!
@VishalS-HK : C, C++, Java, Python

**Comment by VishalS-HK** [comment]
I would like to do it in Java and C only

**Comment by Kumar-laxmi** [comment]
> I would like to do it in Java and C only

ok

**Comment by Dharnish38** [comment]
Please assign this issue to me in Python

**Comment by Dharnish38** [comment]
Please assign this issue to me in Python   @Kumar-laxmi

**Comment by VaibhavArora314** [comment]
@Kumar-laxmi please assign this to me in C++.

**Comment by Kumar-laxmi** [comment]
@VishalS-HK  I have unassigned this issue due to inactivity

**Comment by Kumar-laxmi** [comment]
Assigned!
@VaibhavArora314 : C++
@Dharnish38 : Python

**Comment by goyalh4164** [comment]
@Kumar-laxmi assign this to me in java.

**Comment by Kumar-laxmi** [comment]
@Dharnish38 What is your status on this issue?

**Comment by Dharnish38** [comment]
@Kumar-laxmi Sorry to say like this, I have finished working on this issue but I am not able to create a new pull request for this, because there is a PR already opened by me which is #505 after getting it merged only I can able to create another pull request if I try to create a pull request now this issue will be attach to that PR #505 on top of that it will be double burden for mentors and you again to visualize the changes for that only I am not creating a pull request for this issue. If it's ok for you then I can create a PR no problem on that.

**Comment by Dharnish38** [comment]
@Kumar-laxmi I have opened the pull request for this issue #537.

**Comment by goyalh4164** [comment]
@Kumar-laxmi I have opened the pull request. Kindly take a look.Thanks

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I have opened the pull request. Kindly take a look.Thanks

@goyalh4164 You haven't opened any pull request, if you have opened it kindly send the PR number
