### ISSUE TITLE
Longest common substring

### ISSUE THREAD

**Issue by Volcano-Dragon** [Kumar-laxmi/Algorithms#455]
**Is your feature request related to a problem? Please describe.**
It can be use to find the longest common substring between 2 or more strings.

**Describe the solution you'd like**
The user will enter the 2 strings then the algorithm will try to match the substring to all other arrays after that the longest one will be the output.

**Additional context**
I can do this in Python.

**Comment by kapil4457** [comment]
Is your feature request related to a problem? Please describe.
It can be used to find the longest common substring.

Describe the solution you'd like
As input we will enter 2 strings and traversing through both simultaneously and matching the same characters.

Additional context
I can do this in C++ in O(n) time complexity and O(1) space complexity.

**Comment by dicode04** [comment]
**Is your feature request related to a problem? Please describe.**
This problem is to check for the longest common substring from given 2 strings.

**Describe the solution you'd like.**
As the user will input 2 strings and upon traversing both the strings simultaneously as well as check for the characters it will return the output as a longest common substring.

**Additional context**
I will do this using Java keeping in mind time complexity.

**Comment by Kumar-laxmi** [comment]
refer #286
