### ISSUE TITLE
Diffie - Hellman Algorithm in java

### ISSUE THREAD

**Issue by Durgesh4993** [Kumar-laxmi/Algorithms#687]

**Comment by SPARSH1608** [comment]
**### Description:**
The Diffie-Hellman algorithm is a method used for secure key exchange over an unsecured communication channel. It allows two parties, typically referred to as Alice and Bob, to establish a shared secret key without explicitly transmitting the key

### Feature :
Add Diffie - Hellman Algorithm in  JAVA

### Description of solution :
Will add Diffie - Hellman Algorithm with adequate comments for readers to get a clear understanding.
To add in JAVA

### Alternatives Considered :
Online Resources and Tutorials

@Kumar-laxmi Can you assign me this issue under SSoC '23 so that I can send in a PR on 1st June ?

**Comment by Kumar-laxmi** [comment]
@SPARSH1608 Could you implement this in Java and either C or C++

**Comment by SPARSH1608** [comment]
@Kumar-laxmi yes I can

**Comment by Kumar-laxmi** [comment]
Assigned!
@SPARSH1608 : C, C++ and Java

**Comment by Kumar-laxmi** [comment]
@SPARSH1608 What is your status on this issue?

**Comment by SPARSH1608** [comment]
working on it  @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Kindly complete the implementation within next 3 days or else the issue would be closed and reassigned
