### ISSUE TITLE
 Add Solution for Fractional Knapsack Problem using Dynamic Programming in C++,Python

### ISSUE THREAD

**Issue by manu31shukla** [Kumar-laxmi/Algorithms#688]
**Is your feature request related to a problem? Please describe.**
I would like to propose adding a solution for the Knapsack problem using dynamic programming to the repository. The Knapsack problem is a classic optimization problem where given a set of items with weights and values, the goal is to determine the most valuable combination of items to include in a knapsack without exceeding its weight capacity.

**Describe the solution you'd like**
The proposed solution will utilize dynamic programming techniques to efficiently solve the problem. It will include a C++ implementation that can handle a varying number of items and a given knapsack capacity.

**Describe alternatives you've considered**
The solution will follow the dynamic programming approach, where a 2D table will be used to store intermediate results. It will utilize memoization to avoid redundant calculations and improve performance. The algorithm will determine the optimal combination of items and calculate the maximum value that can be obtained within the given constraints.

**Additional context**
This implementation will be thoroughly tested using different test cases to ensure correctness and efficiency. Additionally, proper documentation and comments will be provided to facilitate understanding and future contributions.

I believe that adding this solution to the repository would be valuable for anyone studying or working on algorithms in C++. It will serve as a useful reference for the Knapsack problem and dynamic programming techniques.

Please let me know if there are any specific guidelines or requirements for contributing to the repository, and I would be happy to address them.

**Comment by Myworld21** [comment]
Greetings!
In Knapsack problem, we are given N items and those items has some weight and profit associated with it. We are also given a bag with capacity W which can hold at most W weight in it. Our target is to put the items into the bag such that the sum of profits associated with them is the maximum possible.
I am capable of solving this issue using both the recursion and memoization methods of Dynamic Programming using C++.
@manu31shukla kindly assign me  this issue for SSOC'23 season 2.
I will also add suitable comments so that it is clearly understandable by the reader.

Thanks.

**Comment by Myworld21** [comment]
Ok ok ..no issue

**Comment by Kumar-laxmi** [comment]
Kindly implement Fractional Knapsack (because 0/1 Knapsack has been implemented in all the languages)

Assigned!
@manu31shukla : C++ & Python
