### ISSUE TITLE
Huffman Coding

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/Algorithms#70]
Huffman Coding is available in the following language:
- Java

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
Can you assign me this issue? I will try to solve this using Java

**Comment by Kumar-laxmi** [comment]
Assigned!
@Priyanshu-Singh-1 : Java

**Comment by ayushete02** [comment]
Assign me this issue i will do it in Python.

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 What is your status because it has been 3 days since you were assigned this issue

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
I have completed my part, but I am not creating the PR because for the 4 issues I have created the PR that has not been merged. Also, it is becoming little chaos, when during merging. This is the PR I am talking about: #184 

So, if you still want I can add my this part to the previous PR. My suggestion is to merge that PR since you have already approved it. So, that I can create a new one for this issue.

@Kumar-laxmi Please tell what to do, so I add my part now, or wait for the previous PR to get merged ?

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

I have also added the Huffman coding in java.
This is the PR containing the mentioned issue. #184

**Comment by Kumar-laxmi** [comment]
This algorithm has been implemented in all four languages
