### ISSUE TITLE
HASHING

### ISSUE THREAD

**Issue by subhamsubham6063** [Kumar-laxmi/Algorithms#943]
**Is your feature request related to a problem? Please describe.**
Basic hashing algorithms in C++, like character hashing and number hashing..

**Comment by killer-mohit** [comment]
Before assigning this issue I would like you to give us the information about what kind of input we are going to have so that I can come up with the best possible hashing techniques for those input data.
I will be very glad to contribute to this project so please assign this issue to me @Kumar-laxmi  under SSOC'23.
